/**
 * ZamTools Localized Search Index
 * Auto-generated by scripts/generate-search-data.js
 */
window.ZAM_LOCALIZED_TOOLS = {
  "en": [
    {
      "id": "image-compressor",
      "key": "imageCompressor",
      "name": "Image Compressor",
      "url": "/tools/image-compressor/",
      "category": "Compress",
      "desc": "Reduce JPG, PNG, and WebP file sizes quickly and safely. Fine-tune your compression quality with a live slider, inspect before-and-after results, and download your optimized files with zero server uploads.",
      "keywords": [
        "image compressor",
        "compress image",
        "reduce image size",
        "compress jpg",
        "compress png",
        "compress webp",
        "shrink image file"
      ]
    },
    {
      "id": "image-resizer",
      "key": "imageResizer",
      "name": "Image Resizer",
      "url": "/tools/image-resizer/",
      "category": "Resize",
      "desc": "Scale your photos to exact pixel widths and heights, standard resolution presets, or exact percentages. Lock aspect ratio to prevent stretching and download instantly with local browser processing.",
      "keywords": [
        "image resizer",
        "resize image",
        "scale image",
        "change photo dimensions",
        "resize picture in pixels",
        "lock aspect ratio"
      ]
    },
    {
      "id": "image-to-target-size",
      "key": "imageToTargetSize",
      "name": "Compress to Target Size",
      "url": "/tools/image-to-target-size/",
      "category": "Compress",
      "desc": "Need an image under 50KB, 100KB, or 200KB for an official government portal, job application, or university form? Set your exact target file size in KB or MB and let our iterative algorithm compress it with optimal clarity.",
      "keywords": [
        "compress to target size",
        "compress image to 50kb",
        "compress image to 100kb",
        "reduce image size in kb",
        "exact file size compressor"
      ]
    },
    {
      "id": "image-cropper",
      "key": "imageCropper",
      "name": "Image Cropper",
      "url": "/tools/image-cropper/",
      "category": "Edit",
      "desc": "Crop and frame your photos with interactive canvas selection. Lock standard aspect ratios like 1:1 square, 4:3 portrait, 16:9 landscape, or freely adjust the crop box to highlight what matters most.",
      "keywords": [
        "image cropper",
        "crop image online",
        "photo cropper",
        "square crop 1:1",
        "crop 16:9 landscape",
        "free photo cropper"
      ]
    },
    {
      "id": "image-rotate-flip",
      "key": "imageRotateFlip",
      "name": "Rotate & Flip Image",
      "url": "/tools/image-rotate-flip/",
      "category": "Edit",
      "desc": "Fix sideways smartphone photos or mirror images horizontally and vertically. Turn photos 90° clockwise, 90° counter-clockwise, or 180° upside down in seconds without quality loss.",
      "keywords": [
        "rotate image",
        "flip image",
        "mirror image online",
        "rotate photo 90 degrees",
        "turn photo upside down",
        "fix photo orientation"
      ]
    },
    {
      "id": "jpg-to-png",
      "key": "jpgToPng",
      "name": "JPG to PNG",
      "url": "/tools/jpg-to-png/",
      "category": "Convert",
      "desc": "Convert JPG photos into lossless PNG format with zero degradation. Preserve crisp typography, diagram lines, and sharp edges without installing desktop software.",
      "keywords": [
        "jpg to png",
        "convert jpg to png",
        "jpeg to png online",
        "lossless png converter",
        "turn jpg into png"
      ]
    },
    {
      "id": "png-to-jpg",
      "key": "pngToGithubJpg",
      "name": "PNG to JPG",
      "url": "/tools/png-to-jpg/",
      "category": "Convert",
      "desc": "Convert large PNG files into lightweight, universally compatible JPG images. Replace transparent backgrounds with custom colors (white, black, or custom) and download optimized JPEGs in seconds.",
      "keywords": [
        "png to jpg",
        "convert png to jpg",
        "png to jpeg online",
        "transparent png to jpg",
        "change png to jpg"
      ]
    },
    {
      "id": "webp-converter",
      "key": "webpConverter",
      "name": "WebP Converter",
      "url": "/tools/webp-converter/",
      "category": "Convert",
      "desc": "Convert JPG and PNG images into modern, highly compressed WebP files, or convert WebP images back into widely compatible JPG and PNG formats. Speed up page loads and boost SEO performance.",
      "keywords": [
        "webp converter",
        "convert to webp",
        "jpg to webp",
        "png to webp",
        "webp to jpg",
        "next gen image format"
      ]
    },
    {
      "id": "image-format-converter",
      "key": "imageFormatConverter",
      "name": "Image Format Converter",
      "url": "/tools/image-format-converter/",
      "category": "Convert",
      "desc": "Convert single or batch images seamlessly between JPG, PNG, and WebP formats. Fine-tune output quality, preserve transparency or solid fills, and download converted files instantly without server uploads.",
      "keywords": [
        "image format converter",
        "batch image converter",
        "convert jpg png webp",
        "change image format online",
        "multi image converter"
      ]
    },
    {
      "id": "grayscale-image",
      "key": "grayscaleImage",
      "name": "Grayscale Image",
      "url": "/tools/grayscale-image/",
      "category": "Edit",
      "desc": "Transform color photos into timeless monochrome and black-and-white graphics. Uses standard ITU-R BT.709 luminance formulas to calculate natural contrast and tone depth.",
      "keywords": [
        "grayscale image",
        "convert to black and white",
        "black and white photo filter",
        "monochrome image online",
        "desaturate photo"
      ]
    },
    {
      "id": "brightness-contrast",
      "key": "brightnessContrast",
      "name": "Brightness & Contrast",
      "url": "/tools/brightness-contrast/",
      "category": "Edit",
      "desc": "Fix dark photos, brighten shadows, and boost color saturation with precision sliders. Preview changes in real time and download corrected photos without heavy editing software.",
      "keywords": [
        "brightness contrast online",
        "adjust brightness image",
        "increase contrast photo",
        "fix underexposed picture",
        "photo lighting adjuster"
      ]
    },
    {
      "id": "blur-sharpen-image",
      "key": "blurSharpenImage",
      "name": "Blur & Sharpen",
      "url": "/tools/blur-sharpen-image/",
      "category": "Edit",
      "desc": "Apply smooth Gaussian blur to obscure background details or enhance sharpness with a 3x3 convolution matrix kernel. Fast, interactive, and processed locally in your browser.",
      "keywords": [
        "blur image online",
        "sharpen image online",
        "gaussian blur photo",
        "increase sharpness picture",
        "unblur edges photo"
      ]
    },
    {
      "id": "image-color-picker",
      "key": "imageColorPicker",
      "name": "Image Color Picker",
      "url": "/tools/image-color-picker/",
      "category": "Color",
      "desc": "Extract exact color codes from any photo with a precision zoom loupe eyedropper. Inspect individual pixels, view HEX, RGB, and HSL formats, and build a saved palette history.",
      "keywords": [
        "image color picker",
        "pick color from image",
        "image eyedropper online",
        "hex code from photo",
        "extract rgb from image"
      ]
    },
    {
      "id": "color-palette-generator",
      "key": "colorPaletteGenerator",
      "name": "Color Palette Generator",
      "url": "/tools/color-palette-generator/",
      "category": "Color",
      "desc": "Extract harmonious color palettes from photographs and artwork using color quantization algorithms. Discover dominant tones, inspect HEX codes, and download beautiful swatch cards.",
      "keywords": [
        "color palette generator",
        "extract palette from image",
        "image color scheme generator",
        "dominant colors photo",
        "photo palette creator"
      ]
    },
    {
      "id": "favicon-generator",
      "key": "faviconGenerator",
      "name": "Favicon Generator",
      "url": "/tools/favicon-generator/",
      "category": "Create",
      "desc": "Transform your logo or brand icon into a complete favicon package. Generate standard 16x16, 32x32, 48x48, and 180x180 Apple Touch Icons with ready-to-copy HTML header code.",
      "keywords": [
        "favicon generator",
        "create favicon online",
        "apple touch icon maker",
        "favicon 32x32",
        "generate favicon html tags"
      ]
    },
    {
      "id": "image-to-base64",
      "key": "imageToBase64",
      "name": "Image to Base64",
      "url": "/tools/image-to-base64/",
      "category": "Developer",
      "desc": "Convert image files into Base64 encoded strings and embeddable Data URLs. Embed images directly into HTML <img> tags, CSS background-image properties, or JSON payloads without external asset requests.",
      "keywords": [
        "image to base64",
        "convert photo to base64",
        "base64 data uri generator",
        "embed image in html css",
        "image to base64 string"
      ]
    },
    {
      "id": "base64-to-image",
      "key": "base64ToImage",
      "name": "Base64 to Image",
      "url": "/tools/base64-to-image/",
      "category": "Developer",
      "desc": "Decode Base64 strings, Data URLs, and embedded image code back into clean, downloadable PNG, JPG, or WebP graphic files. Validate encoding syntax and preview files in seconds.",
      "keywords": [
        "base64 to image",
        "decode base64 to image",
        "base64 to png converter",
        "data uri to jpg",
        "convert base64 string to picture"
      ]
    },
    {
      "id": "social-media-image-resizer",
      "key": "socialMediaImageResizer",
      "name": "Social Media Image Resizer",
      "url": "/tools/social-media-image-resizer/",
      "category": "Resize",
      "desc": "Crop and scale photos to exact platform specifications for Instagram, Facebook, YouTube, LinkedIn, TikTok, and X. Eliminate awkward crops and blurry post previews.",
      "keywords": [
        "social media image resizer",
        "instagram post size",
        "youtube thumbnail resizer",
        "facebook cover photo maker",
        "linkedin banner size"
      ]
    },
    {
      "id": "passport-photo-resizer",
      "key": "passportPhotoResizer",
      "name": "Passport Photo Resizer",
      "url": "/tools/passport-photo-resizer/",
      "category": "Resize",
      "desc": "Crop and align passport photos, visa pictures, and ID cards to exact official international standards. Includes biometric face-alignment guides for US (2x2 inch), UK/Schengen (35x45mm), and Indian passport guidelines.",
      "keywords": [
        "passport photo resizer",
        "2x2 photo crop",
        "35x45mm photo maker",
        "us visa photo size",
        "passport size photo online"
      ]
    },
    {
      "id": "meme-generator",
      "key": "memeGenerator",
      "name": "Meme Generator",
      "url": "/tools/meme-generator/",
      "category": "Create",
      "desc": "Create viral memes in seconds with classic Impact captions or modern text styling. Customize font size, colors, stroke outlines, and moveable text boxes with zero watermarks.",
      "keywords": [
        "meme generator",
        "make a meme online",
        "add text to photo",
        "impact font meme maker",
        "funny meme creator"
      ]
    }
  ],
  "fr": [
    {
      "id": "image-compressor",
      "key": "imageCompressor",
      "name": "Compresseur d'image",
      "url": "/fr/outils/compresseur-image/",
      "category": "Compression",
      "desc": "Réduisez la taille de vos fichiers JPG, PNG et WebP rapidement et sans perte visuelle. Ajustez la qualité de compression en direct avec le curseur, visualisez le résultat avant/après et téléchargez vos images sans aucun transfert sur serveur.",
      "keywords": [
        "compresseur image",
        "compresser image",
        "réduire taille image",
        "compresser jpg",
        "compresser png",
        "compresser webp",
        "optimiser photo"
      ]
    },
    {
      "id": "image-resizer",
      "key": "imageResizer",
      "name": "Redimensionner une image",
      "url": "/fr/outils/redimensionner-image/",
      "category": "Redimensionnement",
      "desc": "Ajustez les dimensions de vos photos en pixels, en pourcentage ou avec des formats prédéfinis. Conservez les proportions d'origine pour éviter toute déformation et téléchargez votre image instantanément.",
      "keywords": [
        "redimensionner image",
        "changer taille photo",
        "modifier pixels image",
        "agrandir photo",
        "diminuer dimensions image"
      ]
    },
    {
      "id": "image-to-target-size",
      "key": "imageToTargetSize",
      "name": "Compresser à une taille cible",
      "url": "/fr/outils/image-taille-cible/",
      "category": "Compression",
      "desc": "Vous devez fournir une photo de moins de 50 Ko, 100 Ko ou 200 Ko pour un formulaire officiel ou une candidature ? Indiquez la taille maximale souhaitée et notre algorithme ajuste automatiquement la qualité optimale.",
      "keywords": [
        "compresser taille cible",
        "réduire photo 50 ko",
        "compresser image 100 ko",
        "taille exacte photo",
        "diminuer taille ko"
      ]
    },
    {
      "id": "image-cropper",
      "key": "imageCropper",
      "name": "Recadrer une image",
      "url": "/fr/outils/recadrer-image/",
      "category": "Retouche",
      "desc": "Cadrez et rognez vos photos avec précision grâce à notre zone de sélection interactive. Verrouillez des ratios standard (carré 1:1, 4:3, 16:9) ou découpez librement la zone de votre choix en toute simplicité.",
      "keywords": [
        "recadrer image",
        "rogner photo en ligne",
        "decouper photo",
        "cadrage 1:1 carre",
        "rogner image 16:9"
      ]
    },
    {
      "id": "image-rotate-flip",
      "key": "imageRotateFlip",
      "name": "Pivoter et retourner une image",
      "url": "/fr/outils/pivoter-retourner-image/",
      "category": "Retouche",
      "desc": "Corrigez l'orientation de photos prises de travers avec votre smartphone ou appliquez un effet miroir. Pivotez à 90° vers la droite, 90° vers la gauche ou retournez vos images verticalement et horizontalement.",
      "keywords": [
        "pivoter image",
        "retourner photo en ligne",
        "effet miroir photo",
        "tourner photo 90 degres",
        "corriger orientation image"
      ]
    },
    {
      "id": "jpg-to-png",
      "key": "jpgToPng",
      "name": "JPG en PNG",
      "url": "/fr/outils/jpg-png/",
      "category": "Conversion",
      "desc": "Transformez vos photos JPG en fichiers PNG de haute qualité avec une compression sans perte. Idéal pour figer la qualité de vos captures d'écran, logos et illustrations sans perte à chaque enregistrement.",
      "keywords": [
        "jpg en png",
        "convertir jpg en png",
        "convertisseur jpeg en png",
        "transformer photo en png",
        "image png haute qualite"
      ]
    },
    {
      "id": "png-to-jpg",
      "key": "pngToGithubJpg",
      "name": "PNG en JPG",
      "url": "/fr/outils/png-jpg/",
      "category": "Conversion",
      "desc": "Transformez vos fichiers PNG volumineux en images JPG légères et universellement compatibles. Remplacez automatiquement les zones transparentes par un fond blanc ou personnalisé et réduisez le poids de vos visuels.",
      "keywords": [
        "png en jpg",
        "convertir png en jpg",
        "convertisseur png en jpeg",
        "png fond transparent en jpg",
        "reduire poids png"
      ]
    },
    {
      "id": "webp-converter",
      "key": "webpConverter",
      "name": "Convertisseur WebP",
      "url": "/fr/outils/convertisseur-webp/",
      "category": "Conversion",
      "desc": "Transformez vos images JPG et PNG au format WebP nouvelle génération, ou reconvertissez des fichiers WebP en JPG et PNG. Accélérez le chargement de vos sites web et améliorez vos scores Core Web Vitals.",
      "keywords": [
        "convertisseur webp",
        "convertir en webp",
        "jpg en webp",
        "png en webp",
        "webp en jpg",
        "format nouvelle generation"
      ]
    },
    {
      "id": "image-format-converter",
      "key": "imageFormatConverter",
      "name": "Convertisseur de format d'image",
      "url": "/fr/outils/convertisseur-format-image/",
      "category": "Conversion",
      "desc": "Basculez librement entre les formats JPG, PNG et WebP, à l'unité ou par lot. Réglez la qualité de sortie, gérez la transparence et téléchargez vos fichiers convertis immédiatement sans aucun transfert distant.",
      "keywords": [
        "convertisseur format image",
        "convertir images par lot",
        "changer format photo",
        "convertir jpg png webp",
        "convertisseur universel photo"
      ]
    },
    {
      "id": "grayscale-image",
      "key": "grayscaleImage",
      "name": "Image en niveaux de gris",
      "url": "/fr/outils/image-niveaux-gris/",
      "category": "Retouche",
      "desc": "Transformez vos photos couleur en élégantes compositions monochromes en noir et blanc. Utilise les formules photométriques standard de luminance pour un contraste et des nuances de gris naturels.",
      "keywords": [
        "image noir et blanc",
        "convertir photo en noir et blanc",
        "niveaux de gris en ligne",
        "filtre monochrome photo",
        "desaturer image"
      ]
    },
    {
      "id": "brightness-contrast",
      "key": "brightnessContrast",
      "name": "Luminosité et contraste",
      "url": "/fr/outils/luminosite-contraste/",
      "category": "Retouche",
      "desc": "Éclaircissez les photos trop sombres, réhaussez les contrastes et ravivez les couleurs avec nos curseurs de précision. Visualisez les changements en direct et téléchargez vos images corrigées sans logiciel complexe.",
      "keywords": [
        "luminosite contraste en ligne",
        "eclaircir photo sombre",
        "augmenter contraste image",
        "corriger exposition photo",
        "regler saturation image"
      ]
    },
    {
      "id": "blur-sharpen-image",
      "key": "blurSharpenImage",
      "name": "Flou et netteté",
      "url": "/fr/outils/flou-nettete/",
      "category": "Retouche",
      "desc": "Appliquez un flou élégant pour masquer des détails confidentiels ou rehaussez la netteté des contours grâce à un filtre de convolution. Rapide, précis et exécuté localement dans votre navigateur.",
      "keywords": [
        "flouter image en ligne",
        "nettete photo en ligne",
        "flou gaussien image",
        "rendre photo plus nette",
        "accentuer contours photo"
      ]
    },
    {
      "id": "image-color-picker",
      "key": "imageColorPicker",
      "name": "Sélecteur de couleur d'image",
      "url": "/fr/outils/selecteur-couleur-image/",
      "category": "Couleur",
      "desc": "Extrayez les codes couleur exacts de vos images grâce à notre pipette avec loupe grossissante de haute précision. Inspectez chaque pixel, lisez les valeurs HEX, RGB et HSL et copiez-les facilement dans votre presse-papiers.",
      "keywords": [
        "selecteur couleur image",
        "pipette photo en ligne",
        "trouver code hex image",
        "extraire couleur photo",
        "code rgb image"
      ]
    },
    {
      "id": "color-palette-generator",
      "key": "colorPaletteGenerator",
      "name": "Générateur de palette de couleurs",
      "url": "/fr/outils/generateur-palette-couleurs/",
      "category": "Couleur",
      "desc": "Extrayez automatiquement les palettes de couleurs dominantes et harmonieuses de vos photos préférées grâce à nos algorithmes de quantification. Visualisez les codes HEX et téléchargez une planche nuancier élégante.",
      "keywords": [
        "generateur palette couleurs",
        "extraire palette photo",
        "nuancier couleurs image",
        "couleurs dominantes photo",
        "palette graphique en ligne"
      ]
    },
    {
      "id": "favicon-generator",
      "key": "faviconGenerator",
      "name": "Générateur de favicon",
      "url": "/fr/outils/generateur-favicon/",
      "category": "Création",
      "desc": "Transformez votre logo en un pack complet de favicons pour votre site web. Générez les formats 16x16, 32x32, 48x48 et 180x180 pour Apple Touch Icon avec le code HTML prêt à copier.",
      "keywords": [
        "generateur favicon",
        "creer favicon en ligne",
        "apple touch icon generateur",
        "favicon 32x32",
        "code html favicon"
      ]
    },
    {
      "id": "image-to-base64",
      "key": "imageToBase64",
      "name": "Image en Base64",
      "url": "/fr/outils/image-base64/",
      "category": "Développeur",
      "desc": "Transformez vos fichiers images en chaînes de caractères Base64 et Data URI. Intégrez vos visuels directement dans des balises HTML <img>, des règles CSS background-image ou des fichiers JSON sans requêtes HTTP externes.",
      "keywords": [
        "image en base64",
        "convertir photo en base64",
        "generateur data uri image",
        "integrer image html css",
        "chaine base64 photo"
      ]
    },
    {
      "id": "base64-to-image",
      "key": "base64ToImage",
      "name": "Base64 en image",
      "url": "/fr/outils/base64-image/",
      "category": "Développeur",
      "desc": "Décodez vos chaînes de caractères Base64 et Data URI pour retrouver des fichiers images téléchargeables en PNG, JPG ou WebP. Validez la syntaxe de votre code et prévisualisez vos visuels en un instant.",
      "keywords": [
        "base64 en image",
        "decoder base64 en photo",
        "convertir data uri en png",
        "base64 en jpg en ligne",
        "transformer texte base64 en image"
      ]
    },
    {
      "id": "social-media-image-resizer",
      "key": "socialMediaImageResizer",
      "name": "Redimensionneur réseaux sociaux",
      "url": "/fr/outils/redimensionneur-images-reseaux-sociaux/",
      "category": "Redimensionnement",
      "desc": "Adaptez vos visuels aux formats officiels d'Instagram, Facebook, YouTube, LinkedIn, TikTok et X. Évitez les recadrages automatiques disgracieux et obtenez des publications impeccables.",
      "keywords": [
        "redimensionner photo reseaux sociaux",
        "taille image instagram",
        "miniature youtube dimensions",
        "banniere linkedin taille",
        "story instagram format"
      ]
    },
    {
      "id": "passport-photo-resizer",
      "key": "passportPhotoResizer",
      "name": "Redimensionneur photo de passeport",
      "url": "/fr/outils/redimensionneur-photo-passeport/",
      "category": "Redimensionnement",
      "desc": "Recadrez et alignez vos photos d'identité aux normes officielles françaises, européennes (35x45 mm) et internationales (États-Unis 2x2 pouces). Guide biométrique visuel pour respecter les exigences administratives.",
      "keywords": [
        "photo identite 35x45 en ligne",
        "recadrer photo passeport",
        "photo visa usa 2x2",
        "norme biométrique photo identite",
        "creer planche photo identite"
      ]
    },
    {
      "id": "meme-generator",
      "key": "memeGenerator",
      "name": "Générateur de mèmes",
      "url": "/fr/outils/generateur-memes/",
      "category": "Création",
      "desc": "Concevez des mèmes viraux en quelques secondes avec la typographie Impact culte ou un style moderne. Personnalisez les textes du haut et du bas, ajustez la taille et téléchargez vos mèmes sans aucun filigrane.",
      "keywords": [
        "generateur de memes",
        "creer un meme en ligne",
        "ajouter texte sur photo",
        "faire un meme gratuit",
        "police impact meme"
      ]
    }
  ],
  "es": [
    {
      "id": "image-compressor",
      "key": "imageCompressor",
      "name": "Compresor de imágenes",
      "url": "/es/herramientas/comprimir-imagen/",
      "category": "Compresión",
      "desc": "Reduce el tamaño de tus fotos JPG, PNG y WebP de forma rápida, eficiente y totalmente segura. Ajusta el nivel de compresión con el deslizador en tiempo real, compara el antes y después y descarga tu imagen optimizada sin subir nada a servidores.",
      "keywords": [
        "comprimir imagen",
        "compresor de fotos",
        "reducir tamano imagen",
        "comprimir jpg",
        "comprimir png",
        "comprimir webp",
        "bajar peso foto"
      ]
    },
    {
      "id": "image-resizer",
      "key": "imageResizer",
      "name": "Redimensionar imagen",
      "url": "/es/herramientas/redimensionar-imagen/",
      "category": "Redimensionar",
      "desc": "Cambia el tamaño de tus fotos en píxeles, porcentaje o mediante resoluciones predeterminadas. Bloquea la relación de aspecto para no deformar la imagen y descarga el resultado al instante con procesamiento 100% local.",
      "keywords": [
        "redimensionar imagen",
        "cambiar tamano foto",
        "escalar imagen",
        "ajustar pixeles foto",
        "modificar resolucion"
      ]
    },
    {
      "id": "image-to-target-size",
      "key": "imageToTargetSize",
      "name": "Comprimir a tamaño exacto",
      "url": "/es/herramientas/imagen-tamano-objetivo/",
      "category": "Compresión",
      "desc": "¿Necesitas que tu foto pese menos de 50KB, 100KB o 200KB para subirla a un portal gubernamental, visado o trámite universitario? Define el peso máximo y nuestro algoritmo ajustará la compresión exacta con la mayor nitidez posible.",
      "keywords": [
        "comprimir a tamano exacto",
        "reducir imagen a 50kb",
        "comprimir foto a 100kb",
        "reducir kb de imagen",
        "tamano limite foto"
      ]
    },
    {
      "id": "image-cropper",
      "key": "imageCropper",
      "name": "Recortar imagen",
      "url": "/es/herramientas/recortar-imagen/",
      "category": "Edición",
      "desc": "Encuadra y recorta tus imágenes fácilmente en el lienzo interactivo. Ajusta proporciones fijas como cuadrado 1:1, 4:3 o panorámico 16:9, o selecciona un área personalizada para resaltar lo más importante.",
      "keywords": [
        "recortar imagen",
        "recortar foto online",
        "encuadrar foto",
        "recorte cuadrado 1:1",
        "recortar imagen 16:9 gratis"
      ]
    },
    {
      "id": "image-rotate-flip",
      "key": "imageRotateFlip",
      "name": "Rotar y voltear imagen",
      "url": "/es/herramientas/rotar-voltear-imagen/",
      "category": "Edición",
      "desc": "Corrige fotos que quedaron de costado o de cabeza al tomarlas con tu móvil. Rota 90° a la derecha, 90° a la izquierda o aplica efecto espejo horizontal y vertical sin perder definición.",
      "keywords": [
        "rotar imagen",
        "voltear foto online",
        "girar foto 90 grados",
        "efecto espejo foto",
        "cambiar orientacion imagen"
      ]
    },
    {
      "id": "jpg-to-png",
      "key": "jpgToPng",
      "name": "JPG a PNG",
      "url": "/es/herramientas/jpg-a-png/",
      "category": "Convertir",
      "desc": "Pasa fotos JPG a formato PNG sin pérdida de calidad. Ideal para capturas de pantalla, esquemas y gráficos donde se requiere máxima definición sin artefactos de compresión JPEG.",
      "keywords": [
        "jpg a png",
        "convertir jpg a png gratis",
        "transformar jpeg en png",
        "convertidor imagen png",
        "cambiar formato a png"
      ]
    },
    {
      "id": "png-to-jpg",
      "key": "pngToGithubJpg",
      "name": "PNG a JPG",
      "url": "/es/herramientas/png-a-jpg/",
      "category": "Convertir",
      "desc": "Convierte archivos PNG pesados en imágenes JPG compactas y compatibles con cualquier dispositivo. Rellena las transparencias con fondos sólidos y ahorra espacio de almacenamiento al instante.",
      "keywords": [
        "png a jpg",
        "convertir png a jpg gratis",
        "transformar png en jpeg",
        "quitar transparencia png a jpg",
        "aligerar imagen png"
      ]
    },
    {
      "id": "webp-converter",
      "key": "webpConverter",
      "name": "Convertidor WebP",
      "url": "/es/herramientas/convertidor-webp/",
      "category": "Convertir",
      "desc": "Transforma imágenes JPG y PNG al moderno formato WebP para aligerar páginas web, o convierte archivos WebP de vuelta a JPG y PNG. Mejora los tiempos de carga y el posicionamiento SEO de tu web.",
      "keywords": [
        "convertidor webp",
        "convertir a webp",
        "jpg a webp",
        "png a webp",
        "webp a jpg online",
        "formato de imagen webp"
      ]
    },
    {
      "id": "image-format-converter",
      "key": "imageFormatConverter",
      "name": "Convertidor de formato de imagen",
      "url": "/es/herramientas/convertidor-formato-imagen/",
      "category": "Convertir",
      "desc": "Convierte fotos de forma individual o por lotes entre JPG, PNG y WebP. Configura la calidad de salida, gestiona fondos transparentes y descarga tus archivos transformados al instante sin enviar nada a servidores.",
      "keywords": [
        "convertidor formato imagen",
        "convertir imagenes por lote",
        "cambiar formato de fotos",
        "convertir jpg png webp online",
        "conversor universal imagen"
      ]
    },
    {
      "id": "grayscale-image",
      "key": "grayscaleImage",
      "name": "Escala de grises",
      "url": "/es/herramientas/escala-grises/",
      "category": "Edición",
      "desc": "Transforma tus fotos a color en clásicas imágenes monocromáticas en blanco y negro. Aplica la fórmula de luminancia estándar para lograr contrastes naturales y profundidad tonal.",
      "keywords": [
        "foto blanco y negro",
        "convertir a escala de grises",
        "filtro blanco y negro online",
        "desaturar foto",
        "imagen monocromatica"
      ]
    },
    {
      "id": "brightness-contrast",
      "key": "brightnessContrast",
      "name": "Brillo y contraste",
      "url": "/es/herramientas/brillo-contraste/",
      "category": "Edición",
      "desc": "Aclara fotografías oscuras, equilibra sombras y resalta los colores con controles deslizantes de precisión. Observa los cambios en vivo y descarga fotos con aspecto profesional sin instalar programas pesados.",
      "keywords": [
        "brillo contraste online",
        "aclarar foto oscura",
        "aumentar contraste imagen",
        "corregir exposicion foto",
        "ajustar saturacion"
      ]
    },
    {
      "id": "blur-sharpen-image",
      "key": "blurSharpenImage",
      "name": "Desenfocar y enfocar",
      "url": "/es/herramientas/desenfocar-enfocar/",
      "category": "Edición",
      "desc": "Aplica desenfoque suave para difuminar fondos o destaca contornos y texturas con una matriz de enfoque por convolución. Ajuste en tiempo real y procesamiento 100% privado.",
      "keywords": [
        "desenfocar imagen online",
        "aumentar nitidez foto",
        "desenfoque gaussiano online",
        "enfocar foto borrosa",
        "resaltar bordes imagen"
      ]
    },
    {
      "id": "image-color-picker",
      "key": "imageColorPicker",
      "name": "Selector de color de imagen",
      "url": "/es/herramientas/selector-color-imagen/",
      "category": "Color",
      "desc": "Obtén los códigos de color exactos de cualquier imagen con un cuentagotas de precisión con lupa de aumento 8x. Inspecciona píxeles individuales, obtén formatos HEX, RGB y HSL y copia el código al portapapeles con un clic.",
      "keywords": [
        "selector de color imagen",
        "cuentagotas online foto",
        "sacar codigo hex imagen",
        "extraer colores de foto",
        "codigo rgb de imagen"
      ]
    },
    {
      "id": "color-palette-generator",
      "key": "colorPaletteGenerator",
      "name": "Generador de paleta de colores",
      "url": "/es/herramientas/generador-paleta-colores/",
      "category": "Color",
      "desc": "Extrae paletas de colores armónicas y profesionales a partir de cualquier fotografía o diseño. Descubre las tonalidades predominantes, revisa los códigos HEX y descarga una tarjeta de muestras lista para presentar.",
      "keywords": [
        "generador paleta colores",
        "extraer paleta de foto",
        "paleta de colores imagen online",
        "colores dominantes foto",
        "crear muestras de color"
      ]
    },
    {
      "id": "favicon-generator",
      "key": "faviconGenerator",
      "name": "Generador de favicon",
      "url": "/es/herramientas/generador-favicon/",
      "category": "Crear",
      "desc": "Transforma tu logotipo en un conjunto completo de favicons para tu página web. Genera los tamaños estándar 16x16, 32x32, 48x48 y el icono Apple Touch de 180x180 con el código HTML listo para pegar.",
      "keywords": [
        "generador favicon",
        "crear favicon online",
        "apple touch icon generator",
        "icono para pagina web",
        "etiquetas html favicon"
      ]
    },
    {
      "id": "image-to-base64",
      "key": "imageToBase64",
      "name": "Imagen a Base64",
      "url": "/es/herramientas/imagen-a-base64/",
      "category": "Desarrollador",
      "desc": "Convierte archivos de imagen en cadenas codificadas en Base64 y Data URLs. Incrusta gráficos directamente en etiquetas HTML <img>, propiedades CSS background-image o payloads JSON sin necesidad de alojar archivos externos.",
      "keywords": [
        "imagen a base64",
        "convertir foto a base64",
        "generador data uri",
        "incrustar imagen en html css",
        "cadena base64 imagen"
      ]
    },
    {
      "id": "base64-to-image",
      "key": "base64ToImage",
      "name": "Base64 a imagen",
      "url": "/es/herramientas/base64-a-imagen/",
      "category": "Desarrollador",
      "desc": "Decodifica texto Base64 y Data URLs para reconstruir archivos de imagen limpios y descargables en PNG, JPG o WebP. Verifica la sintaxis del código y guarda tus imágenes en segundos.",
      "keywords": [
        "base64 a imagen",
        "decodificar base64 a foto",
        "convertir data uri a png",
        "base64 a jpg online",
        "pasar texto base64 a imagen"
      ]
    },
    {
      "id": "social-media-image-resizer",
      "key": "socialMediaImageResizer",
      "name": "Redimensionador para redes sociales",
      "url": "/es/herramientas/redimensionador-redes-sociales/",
      "category": "Redimensionar",
      "desc": "Adapta tus fotos a las dimensiones exactas de Instagram, Facebook, YouTube, LinkedIn, TikTok y X. Evita cortes incómodos y asegura que tus publicaciones se vean profesionales en cualquier pantalla.",
      "keywords": [
        "tamano fotos redes sociales",
        "medidas post instagram",
        "tamano miniatura youtube",
        "portada facebook medidas",
        "tamano imagen linkedin"
      ]
    },
    {
      "id": "passport-photo-resizer",
      "key": "passportPhotoResizer",
      "name": "Redimensionador foto de pasaporte",
      "url": "/es/herramientas/redimensionador-foto-pasaporte/",
      "category": "Redimensionar",
      "desc": "Recorta y alinea fotos para pasaporte, carnet de identidad y visas según los estándares internacionales. Incluye guía facial biométrica para España/Schengen (35x45mm) y visa estadounidense (2x2 pulgadas).",
      "keywords": [
        "foto carnet online",
        "tamano foto pasaporte",
        "foto visa americana 2x2",
        "recortar foto 35x45",
        "imprimir fotos carnet"
      ]
    },
    {
      "id": "meme-generator",
      "key": "memeGenerator",
      "name": "Generador de memes",
      "url": "/es/herramientas/generador-memes/",
      "category": "Crear",
      "desc": "Crea memes virales en segundos con el clásico formato de texto superior e inferior. Elige tamaño de letra, ajusta bordes negros y descarga tus memes sin marcas de agua ni suscripciones.",
      "keywords": [
        "generador de memes",
        "crear meme online gratis",
        "poner texto en fotos",
        "hacer memes online",
        "fuente impact memes"
      ]
    }
  ],
  "id": [
    {
      "id": "image-compressor",
      "key": "imageCompressor",
      "name": "Kompres Gambar",
      "url": "/id/alat/kompres-gambar/",
      "category": "Kompresi",
      "desc": "Perkecil ukuran file gambar JPG, PNG, dan WebP dengan cepat dan aman. Sesuaikan kualitas menggunakan slider interaktif, bandingkan hasil sebelum dan sesudah kompresi, lalu unduh hasilnya tanpa mengunggah file ke server mana pun.",
      "keywords": [
        "kompres gambar",
        "perkecil ukuran foto",
        "kompres jpg",
        "kompres png",
        "kompres foto online",
        "kurangi kb foto",
        "kompres webp"
      ]
    },
    {
      "id": "image-resizer",
      "key": "imageResizer",
      "name": "Ubah Ukuran Gambar",
      "url": "/id/alat/ubah-ukuran-gambar/",
      "category": "Ubah Ukuran",
      "desc": "Sesuaikan dimensi foto Anda ke ukuran piksel yang tepat, persentase skala, atau resolusi standar. Kunci rasio aspek agar foto tidak melar atau terdistorsi, lalu unduh hasilnya secara instan.",
      "keywords": [
        "ubah ukuran gambar",
        "resize foto online",
        "ganti resolusi foto",
        "skala gambar piksel",
        "perkecil dimensi foto"
      ]
    },
    {
      "id": "image-to-target-size",
      "key": "imageToTargetSize",
      "name": "Kompres ke Ukuran Target",
      "url": "/id/alat/kompres-ke-ukuran-target/",
      "category": "Kompresi",
      "desc": "Butuh foto berukuran di bawah 50KB, 100KB, atau 200KB untuk pendaftaran kerja, syarat beasiswa, atau portal pemerintah? Tentukan batas maksimal ukuran file Anda dalam KB atau MB, dan biarkan algoritma kami mengoptimalkannya.",
      "keywords": [
        "kompres foto ke 50kb",
        "kompres gambar 100kb",
        "perkecil foto 200kb",
        "kompres ukuran tepat",
        "syarat cpns foto"
      ]
    },
    {
      "id": "image-cropper",
      "key": "imageCropper",
      "name": "Potong Gambar",
      "url": "/id/alat/potong-gambar/",
      "category": "Edit",
      "desc": "Potong dan atur fokus gambar Anda dengan kanvas interaktif. Gunakan rasio standar seperti kotak 1:1, potret 4:3, lanskap 16:9, atau atur bingkai secara bebas untuk menonjolkan bagian terpenting foto.",
      "keywords": [
        "potong gambar",
        "crop foto online",
        "crop gambar kotak 1:1",
        "potong foto 16:9",
        "crop foto gratis"
      ]
    },
    {
      "id": "image-rotate-flip",
      "key": "imageRotateFlip",
      "name": "Putar dan Balik Gambar",
      "url": "/id/alat/putar-balik-gambar/",
      "category": "Edit",
      "desc": "Perbaiki foto miring atau terbalik hasil jepretan kamera ponsel. Putar foto 90° ke kanan, 90° ke kiri, 180°, atau buat efek cermin (mirror) horizontal dan vertikal dengan mudah.",
      "keywords": [
        "putar gambar",
        "rotasi foto online",
        "balik gambar horizontal",
        "mirror foto online",
        "perbaiki foto miring"
      ]
    },
    {
      "id": "jpg-to-png",
      "key": "jpgToPng",
      "name": "JPG ke PNG",
      "url": "/id/alat/jpg-ke-png/",
      "category": "Konversi",
      "desc": "Ubah file gambar JPG menjadi PNG berkualitas tinggi tanpa kompresi yang merusak. Sangat pas untuk tangkapan layar, logo, dan diagram yang membutuhkan garis tepi bersih dan warna akurat.",
      "keywords": [
        "jpg ke png",
        "konversi jpg ke png",
        "ubah jpg ke png online",
        "format png tanpa pecah",
        "ganti jpeg ke png"
      ]
    },
    {
      "id": "png-to-jpg",
      "key": "pngToGithubJpg",
      "name": "PNG ke JPG",
      "url": "/id/alat/png-ke-jpg/",
      "category": "Konversi",
      "desc": "Ubah file PNG yang berat menjadi gambar JPG yang ringan dan kompatibel di semua aplikasi. Ganti area transparan dengan latar warna solid dan unduh hasilnya dalam hitungan detik.",
      "keywords": [
        "png ke jpg",
        "konversi png ke jpg",
        "ubah png jadi jpg",
        "hilangkan transparan png ke jpg",
        "perkecil ukuran png"
      ]
    },
    {
      "id": "webp-converter",
      "key": "webpConverter",
      "name": "Konverter WebP",
      "url": "/id/alat/konverter-webp/",
      "category": "Konversi",
      "desc": "Ubah foto JPG dan PNG ke format WebP mutakhir untuk mempercepat situs web, atau ubah kembali file WebP ke format JPG dan PNG yang umum. Tingkatkan skor Core Web Vitals dan kecepatan website Anda.",
      "keywords": [
        "konverter webp",
        "ubah ke webp",
        "jpg ke webp",
        "png ke webp",
        "webp ke jpg",
        "format web generasi baru"
      ]
    },
    {
      "id": "image-format-converter",
      "key": "imageFormatConverter",
      "name": "Konverter Format Gambar",
      "url": "/id/alat/konverter-format-gambar/",
      "category": "Konversi",
      "desc": "Ubah format foto satuan maupun banyak sekaligus (batch) antara JPG, PNG, dan WebP. Atur kualitas kompresi, sesuaikan transparansi, dan unduh hasilnya seketika tanpa perlu mengunggah file ke server luar.",
      "keywords": [
        "konverter format gambar",
        "konversi gambar batch",
        "ubah format foto online",
        "konversi jpg png webp",
        "ganti format banyak foto"
      ]
    },
    {
      "id": "grayscale-image",
      "key": "grayscaleImage",
      "name": "Gambar Skala Abu-abu",
      "url": "/id/alat/gambar-skala-abu-abu/",
      "category": "Edit",
      "desc": "Ubah foto berwarna menjadi gambar monokrom hitam putih yang klasik dan elegan. Menggunakan rumus pencahayaan standar untuk menghasilkan gradasi abu-abu yang alami dan seimbang.",
      "keywords": [
        "foto hitam putih",
        "ubah ke grayscale online",
        "filter hitam putih",
        "foto monokrom online",
        "desaturasi warna foto"
      ]
    },
    {
      "id": "brightness-contrast",
      "key": "brightnessContrast",
      "name": "Kecerahan & Kontras",
      "url": "/id/alat/kecerahan-kontras/",
      "category": "Edit",
      "desc": "Perbaiki foto yang terlalu gelap, seimbangkan bayangan, dan buat warna foto lebih hidup dengan slider presisi. Lihat pratinjau langsung dan unduh foto yang disempurnakan tanpa aplikasi edit yang rumit.",
      "keywords": [
        "atur kecerahan foto",
        "terangkan foto gelap online",
        "tambah kontras gambar",
        "kecerahan kontras online",
        "atur saturasi foto"
      ]
    },
    {
      "id": "blur-sharpen-image",
      "key": "blurSharpenImage",
      "name": "Buramkan & Pertajam Gambar",
      "url": "/id/alat/buram-pertajam-gambar/",
      "category": "Edit",
      "desc": "Berikan efek blur lembut untuk menyamarkan detail latar belakang atau pertajam garis tepi foto yang kurang fokus dengan filter konvolusi. Cepat, interaktif, dan aman di perangkat Anda.",
      "keywords": [
        "buramkan foto online",
        "pertajam foto buram",
        "efek blur gambar",
        "menajamkan foto",
        "filter ketajaman gambar"
      ]
    },
    {
      "id": "image-color-picker",
      "key": "imageColorPicker",
      "name": "Pemilih Warna Gambar",
      "url": "/id/alat/pemilih-warna-gambar/",
      "category": "Warna",
      "desc": "Dapatkan kode warna akurat dari foto dengan alat pipet warna pembesar 8x. Periksa warna tiap piksel dengan detail, lihat kode format HEX, RGB, dan HSL, lalu salin langsung ke clipboard Anda.",
      "keywords": [
        "pemilih warna gambar",
        "pipet warna foto online",
        "ambil kode hex foto",
        "cari warna gambar",
        "ekstrak kode rgb foto"
      ]
    },
    {
      "id": "color-palette-generator",
      "key": "colorPaletteGenerator",
      "name": "Generator Palet Warna",
      "url": "/id/alat/generator-palet-warna/",
      "category": "Warna",
      "desc": "Ekstrak skema warna yang harmonis dari foto atau karya seni favorit Anda. Temukan rona warna dominan, lihat kode HEX secara instan, dan unduh kartu sampel warna untuk proyek desain Anda.",
      "keywords": [
        "generator palet warna",
        "ekstrak palet dari foto",
        "skema warna gambar online",
        "warna dominan foto",
        "buat palet warna foto"
      ]
    },
    {
      "id": "favicon-generator",
      "key": "faviconGenerator",
      "name": "Generator Favicon",
      "url": "/id/alat/generator-favicon/",
      "category": "Buat",
      "desc": "Ubah logo atau gambar Anda menjadi paket favicon lengkap untuk website. Hasilkan ukuran standar 16x16, 32x32, 48x48, dan 180x180 px (Apple Touch Icon) lengkap dengan cuplikan kode HTML yang siap ditempel.",
      "keywords": [
        "generator favicon",
        "buat favicon online",
        "bikin ikon website",
        "favicon 32x32",
        "kode html favicon"
      ]
    },
    {
      "id": "image-to-base64",
      "key": "imageToBase64",
      "name": "Gambar ke Base64",
      "url": "/id/alat/gambar-ke-base64/",
      "category": "Developer",
      "desc": "Ubah file gambar menjadi kode string Base64 dan format Data URL. Sematkan gambar langsung ke dalam tag HTML <img>, properti CSS background-image, atau data JSON tanpa perlu membuat request file terpisah.",
      "keywords": [
        "gambar ke base64",
        "konversi foto ke base64",
        "generator data uri",
        "embed gambar html css",
        "string base64 gambar"
      ]
    },
    {
      "id": "base64-to-image",
      "key": "base64ToImage",
      "name": "Base64 ke Gambar",
      "url": "/id/alat/base64-ke-gambar/",
      "category": "Developer",
      "desc": "Dekode teks string Base64 dan Data URL menjadi file gambar asli berformat PNG, JPG, atau WebP yang dapat diunduh. Uji kevalidan kode dan lihat pratinjau foto secara instan tanpa server luar.",
      "keywords": [
        "base64 ke gambar",
        "decode base64 foto",
        "ubah data uri ke png",
        "konversi string base64 jadi gambar",
        "base64 ke jpg"
      ]
    },
    {
      "id": "social-media-image-resizer",
      "key": "socialMediaImageResizer",
      "name": "Pengubah Ukuran Media Sosial",
      "url": "/id/alat/pengubah-ukuran-media-sosial/",
      "category": "Ubah Ukuran",
      "desc": "Sesuaikan ukuran foto Anda dengan spesifikasi resmi Instagram, Facebook, YouTube, LinkedIn, TikTok, dan X. Hindari cropping otomatis yang merusak tampilan postingan Anda.",
      "keywords": [
        "ukuran foto instagram",
        "ukuran thumbnail youtube",
        "banner linkedin ukuran",
        "story instagram ukuran",
        "resize foto sosmed"
      ]
    },
    {
      "id": "passport-photo-resizer",
      "key": "passportPhotoResizer",
      "name": "Pengubah Ukuran Foto Paspor",
      "url": "/id/alat/pengubah-ukuran-foto-paspor/",
      "category": "Ubah Ukuran",
      "desc": "Sesuaikan pas foto untuk paspor, visa, dan KTP dengan standar resmi. Dilengkapi panduan biometrik wajah untuk ukuran standar Indonesia (3x4 cm, 4x6 cm), visa AS (2x2 inci), dan paspor internasional.",
      "keywords": [
        "pas foto 3x4 online",
        "ukuran foto paspor 4x6",
        "foto visa 2x2 inci",
        "crop pas foto online",
        "cetak pas foto"
      ]
    },
    {
      "id": "meme-generator",
      "key": "memeGenerator",
      "name": "Generator Meme",
      "url": "/id/alat/generator-meme/",
      "category": "Buat",
      "desc": "Buat meme lucu yang siap viral dalam hitungan detik. Tambahkan teks atas dan bawah dengan font Impact klasik, sesuaikan ukuran teks dan warna garis luar, lalu unduh secara bebas tanpa watermark.",
      "keywords": [
        "pembuat meme online",
        "bikin meme gratis",
        "tambah tulisan di foto",
        "generator meme indonesia",
        "buat meme tanpa watermark"
      ]
    }
  ],
  "de": [
    {
      "id": "image-compressor",
      "key": "imageCompressor",
      "name": "Bild komprimieren",
      "url": "/de/tools/bild-komprimieren/",
      "category": "Komprimieren",
      "desc": "Reduzieren Sie die Dateigröße von JPG-, PNG- und WebP-Bildern schnell, verlustarm und datensicher. Stellen Sie die Kompressionsstufe stufenlos ein, vergleichen Sie Vorher/Nachher direkt im Browser und laden Sie das optimierte Bild ohne Server-Upload herunter.",
      "keywords": [
        "bild komprimieren",
        "bild verkleinern dateigroesse",
        "jpg komprimieren",
        "png komprimieren",
        "foto komprimieren online",
        "webp komprimieren"
      ]
    },
    {
      "id": "image-resizer",
      "key": "imageResizer",
      "name": "Bild skalieren",
      "url": "/de/tools/bild-skalieren/",
      "category": "Skalieren",
      "desc": "Skalieren Sie Fotos auf exakte Pixelabmessungen, Prozentwerte oder Standardauflösungen. Behalten Sie das Seitenverhältnis bei, um Verzerrungen zu vermeiden, und laden Sie Ihr Bild ohne Qualitätsverlust herunter.",
      "keywords": [
        "bildgroesse aendern",
        "bild skalieren online",
        "pixel maße bild aendern",
        "foto verkleinern pixel",
        "seitenverhaeltnis bild"
      ]
    },
    {
      "id": "image-to-target-size",
      "key": "imageToTargetSize",
      "name": "Bild auf Zielgröße komprimieren",
      "url": "/de/tools/bild-zielgroesse/",
      "category": "Komprimieren",
      "desc": "Müssen Sie ein Foto auf unter 50 KB, 100 KB oder 200 KB für ein Bewerbungsportal, Visaantrag oder Universitätsformular bringen? Geben Sie Ihre gewünschte Obergrenze in KB oder MB ein – unser Algorithmus ermittelt automatisch die beste Qualität.",
      "keywords": [
        "bild auf 50kb komprimieren",
        "bild auf 100kb komprimieren",
        "zielgroesse bild komprimieren",
        "foto dateigroesse begrenzen",
        "kb reduzierer"
      ]
    },
    {
      "id": "image-cropper",
      "key": "imageCropper",
      "name": "Bild zuschneiden",
      "url": "/de/tools/bild-zuschneiden/",
      "category": "Bearbeiten",
      "desc": "Wählen Sie Bildausschnitte präzise mit dem interaktiven Auswahlrahmen. Nutzen Sie feste Standard-Seitenverhältnisse wie quadratisch 1:1, 4:3, 16:9 oder schneiden Sie frei nach Belieben zu.",
      "keywords": [
        "bild zuschneiden",
        "foto beschneiden online",
        "ausschnitt waehlen bild",
        "quadratisch 1:1 zuschneiden",
        "bild 16:9 beschneiden"
      ]
    },
    {
      "id": "image-rotate-flip",
      "key": "imageRotateFlip",
      "name": "Bild drehen & spiegeln",
      "url": "/de/tools/bild-drehen-spiegeln/",
      "category": "Bearbeiten",
      "desc": "Korrigieren Sie versehentlich quer aufgenommene Smartphone-Fotos oder spiegeln Sie Bilder horizontal und vertikal. Drehen Sie Bilder um 90° im oder gegen den Uhrzeigersinn ohne Schärfeverlust.",
      "keywords": [
        "bild drehen online",
        "foto spiegeln",
        "bild um 90 grad drehen",
        "spiegeleffekt foto",
        "bildausrichtung korrigieren"
      ]
    },
    {
      "id": "jpg-to-png",
      "key": "jpgToPng",
      "name": "JPG in PNG",
      "url": "/de/tools/jpg-in-png/",
      "category": "Konvertieren",
      "desc": "Wandeln Sie JPG-Fotos in das verlustfreie PNG-Format um. Ideal für Screenshots, Grafiken und Skizzen, bei denen feine Kanten und klare Typografie ohne Kompressionsartefakte erhalten bleiben sollen.",
      "keywords": [
        "jpg in png",
        "jpg zu png konvertieren",
        "jpeg in png umwandeln online",
        "bildformat png",
        "verlustfrei konvertieren"
      ]
    },
    {
      "id": "png-to-jpg",
      "key": "pngToGithubJpg",
      "name": "PNG in JPG",
      "url": "/de/tools/png-in-jpg/",
      "category": "Konvertieren",
      "desc": "Wandeln Sie speicherintensive PNG-Dateien in kompakte, universell lesbare JPG-Bilder um. Ersetzen Sie transparente Bildbereiche durch weiße oder farbige Hintergründe und sparen Sie wertvollen Speicherplatz.",
      "keywords": [
        "png in jpg",
        "png in jpg umwandeln",
        "transparenz png in jpg hintergrund",
        "png dateigroesse verringern",
        "foto konverter png jpg"
      ]
    },
    {
      "id": "webp-converter",
      "key": "webpConverter",
      "name": "WebP-Konverter",
      "url": "/de/tools/webp-konverter/",
      "category": "Konvertieren",
      "desc": "Wandeln Sie JPG- und PNG-Bilder in das moderne, hocheffiziente WebP-Format um oder konvertieren Sie WebP-Dateien zurück in kompatibles JPG und PNG. Beschleunigen Sie Ihre Webseiten und optimieren Sie Ihre Core Web Vitals.",
      "keywords": [
        "webp konverter",
        "in webp umwandeln",
        "jpg in webp",
        "png in webp",
        "webp in jpg",
        "next gen bildformat"
      ]
    },
    {
      "id": "image-format-converter",
      "key": "imageFormatConverter",
      "name": "Bildformat-Konverter",
      "url": "/de/tools/bildformat-konverter/",
      "category": "Konvertieren",
      "desc": "Wandeln Sie einzelne Bilder oder ganze Bilderserien flexibel zwischen den Formaten JPG, PNG und WebP um. Passen Sie die Qualität an, steuern Sie Hintergrundfüllungen und laden Sie die Ergebnisse sofort ohne Server-Upload herunter.",
      "keywords": [
        "bildformat konverter",
        "bilder stapelweise konvertieren",
        "jpg png webp umwandeln",
        "bildformat aendern online",
        "batch bildkonverter"
      ]
    },
    {
      "id": "grayscale-image",
      "key": "grayscaleImage",
      "name": "Bild in Graustufen umwandeln",
      "url": "/de/tools/bild-graustufen/",
      "category": "Bearbeiten",
      "desc": "Verwandeln Sie Farbfotografien in zeitlose Schwarz-Weiß-Aufnahmen. Nutzt die fotometrische ITU-R BT.709 Luminanz-Formel für natürliche Graustufen und ausgewogene Kontraste.",
      "keywords": [
        "bild schwarz weiss umwandeln",
        "graustufen bild online",
        "foto entfaerben",
        "monochrom bild konverter",
        "schwarz weiss filter"
      ]
    },
    {
      "id": "brightness-contrast",
      "key": "brightnessContrast",
      "name": "Helligkeit & Kontrast anpassen",
      "url": "/de/tools/helligkeit-kontrast/",
      "category": "Bearbeiten",
      "desc": "Hellen Sie unterbelichtete Fotos auf, optimieren Sie Schatten und verleihen Sie Farben neue Frische mit präzisen Schiebereglern. Betrachten Sie Änderungen in Echtzeit und laden Sie korrigierte Bilder ohne schwere Software herunter.",
      "keywords": [
        "helligkeit kontrast online",
        "dunkles bild aufhellen",
        "kontrast erhoehen bild",
        "foto belichtung anpassen",
        "farbsaettigung bild online"
      ]
    },
    {
      "id": "blur-sharpen-image",
      "key": "blurSharpenImage",
      "name": "Bild weichzeichnen & schärfen",
      "url": "/de/tools/bild-unschaerfe-schaerfen/",
      "category": "Bearbeiten",
      "desc": "Wenden Sie einen weichen Gaußschen Unschärfeeffekt an, um störende Hintergründe abzumildern, oder verstärken Sie Kantenkontraste mit einer präzisen Faltungsmatrix. Schnell, interaktiv und privat im Browser.",
      "keywords": [
        "bild weichzeichnen online",
        "bild schaerfen online",
        "gausscher weichzeichner foto",
        "unscharfes bild schaerfen",
        "kantenschaerfe foto"
      ]
    },
    {
      "id": "image-color-picker",
      "key": "imageColorPicker",
      "name": "Farbpipette online",
      "url": "/de/tools/bild-farbpipette/",
      "category": "Farbe",
      "desc": "Ermitteln Sie exakte Farbcodes aus jedem beliebigen Bild mit unserer integrierten 8x Zoom-Lupe. Prüfen Sie einzelne Pixel, lesen Sie HEX-, RGB- und HSL-Werte ab und kopieren Sie diese direkt in die Zwischenablage.",
      "keywords": [
        "farbpipette online",
        "farbe aus bild ermitteln",
        "hex code foto finden",
        "rgb werte bild auslesen",
        "color picker online"
      ]
    },
    {
      "id": "color-palette-generator",
      "key": "colorPaletteGenerator",
      "name": "Farbpaletten-Generator",
      "url": "/de/tools/farbpaletten-generator/",
      "category": "Farbe",
      "desc": "Extrahieren Sie stimmungsvolle Farbpaletten aus Fotografien und Kunstwerken. Entdecken Sie dominante Farbtöne, prüfen Sie HEX-Werte und laden Sie ansprechende Farbmuster-Karten für Ihre Entwürfe herunter.",
      "keywords": [
        "farbpalette aus bild",
        "farbschema foto online",
        "farben aus bild extrahieren",
        "palette generator foto",
        "dominante farben finden"
      ]
    },
    {
      "id": "favicon-generator",
      "key": "faviconGenerator",
      "name": "Favicon-Generator",
      "url": "/de/tools/favicon-generator/",
      "category": "Erstellen",
      "desc": "Verwandeln Sie Ihr Logo in ein professionelles Favicon-Paket für moderne Webseiten. Erstellen Sie Standardgrößen in 16x16, 32x32, 48x48 und 180x180 px (Apple Touch Icon) inklusive fertigem HTML-Header-Code.",
      "keywords": [
        "favicon generator online",
        "favicon erstellen",
        "apple touch icon generator",
        "website icon erstellen",
        "favicon html code"
      ]
    },
    {
      "id": "image-to-base64",
      "key": "imageToBase64",
      "name": "Bild in Base64 umwandeln",
      "url": "/de/tools/bild-in-base64/",
      "category": "Entwickler",
      "desc": "Konvertieren Sie Bilddateien in Base64-codierte Zeichenfolgen und Data URLs. Binden Sie Grafiken direkt in HTML-Tags <img>, CSS-Hintergründe oder JSON-Schnittstellen ein, ohne zusätzliche Serveranfragen auszulösen.",
      "keywords": [
        "bild in base64 umwandeln",
        "foto zu base64 konvertieren",
        "base64 data uri generator",
        "grafik in html css einbinden",
        "base64 string bild"
      ]
    },
    {
      "id": "base64-to-image",
      "key": "base64ToImage",
      "name": "Base64 in Bild umwandeln",
      "url": "/de/tools/base64-in-bild/",
      "category": "Entwickler",
      "desc": "Decodieren Sie Base64-Strings und Data URLs zurück in saubere, herunterladbare PNG-, JPG- oder WebP-Bilddateien. Prüfen Sie die Codierungssyntax und betrachten Sie Grafiken in Sekundenschnelle.",
      "keywords": [
        "base64 in bild umwandeln",
        "base64 decodieren bild",
        "data uri in png umwandeln",
        "base64 string in foto konvertieren",
        "base64 to jpg online"
      ]
    },
    {
      "id": "social-media-image-resizer",
      "key": "socialMediaImageResizer",
      "name": "Social Media Bildgröße anpassen",
      "url": "/de/tools/social-media-bild-groesse/",
      "category": "Skalieren",
      "desc": "Bringen Sie Fotos und Grafiken auf die exakten Vorgaben von Instagram, Facebook, YouTube, LinkedIn, TikTok und X. Verhindern Sie ungewollte automatische Bildschnitte und unscharfe Posts.",
      "keywords": [
        "social media bildgroessen",
        "instagram post format",
        "youtube thumbnail groesse",
        "facebook titelbild maße",
        "linkedin banner format"
      ]
    },
    {
      "id": "passport-photo-resizer",
      "key": "passportPhotoResizer",
      "name": "Passfoto-Größe anpassen",
      "url": "/de/tools/passfoto-generator-groesse/",
      "category": "Skalieren",
      "desc": "Schneiden Sie Passbilder für Personalausweis, Reisepass, Führerschein und Visa nach offiziellen biometrischen Vorgaben zu. Integrierte Gesichtsschablone für 35x45 mm (EU/Deutschland) und US-Visum (2x2 Zoll).",
      "keywords": [
        "passfoto 35x45 zuschneiden",
        "biometrisches passbild online",
        "passfoto generator",
        "us visum foto 2x2",
        "passbilder drucken"
      ]
    },
    {
      "id": "meme-generator",
      "key": "memeGenerator",
      "name": "Meme-Generator",
      "url": "/de/tools/meme-generator/",
      "category": "Erstellen",
      "desc": "Erstellen Sie virale Memes in Sekundenschnelle mit klassischer Impact-Typografie oder modernem Textstyling. Passen Sie Schriftgröße und Konturen flexibel an und laden Sie Ihre Memes komplett ohne Wasserzeichen herunter.",
      "keywords": [
        "meme generator online",
        "memes erstellen kostenlos",
        "text auf bild schreiben",
        "impact schriftart meme",
        "meme maker ohne wasserzeichen"
      ]
    }
  ],
  "pt": [
    {
      "id": "image-compressor",
      "key": "imageCompressor",
      "name": "Comprimir imagem",
      "url": "/pt/ferramentas/comprimir-imagem/",
      "category": "Compressão",
      "desc": "Reduza o tamanho de fotos JPG, PNG e WebP com máxima rapidez, nitidez e privacidade. Ajuste a qualidade em tempo real com a barra deslizante, inspecione a comparação antes/depois e baixe suas imagens sem enviar nada para servidores externos.",
      "keywords": [
        "comprimir imagem",
        "reduzir tamanho foto",
        "comprimir jpg",
        "comprimir png",
        "diminuir kb foto",
        "otimizar imagem",
        "comprimir webp"
      ]
    },
    {
      "id": "image-resizer",
      "key": "imageResizer",
      "name": "Redimensionar imagem",
      "url": "/pt/ferramentas/redimensionar-imagem/",
      "category": "Redimensionar",
      "desc": "Altere as dimensões das suas fotos para medidas exatas em pixels, porcentagens ou predefinições de resolução. Mantenha a proporção original para evitar distorções e baixe o arquivo otimizado com segurança.",
      "keywords": [
        "redimensionar imagem",
        "mudar tamanho foto",
        "ajustar pixels foto",
        "escalar imagem online",
        "alterar resolucao imagem"
      ]
    },
    {
      "id": "image-to-target-size",
      "key": "imageToTargetSize",
      "name": "Comprimir para tamanho alvo",
      "url": "/pt/ferramentas/imagem-tamanho-alvo/",
      "category": "Compressão",
      "desc": "Precisa enviar uma foto com menos de 50KB, 100KB ou 200KB para um concurso público, visto ou portal institucional? Defina o limite exato em KB ou MB e nosso algoritmo encontrará a melhor qualidade possível.",
      "keywords": [
        "comprimir para 50kb",
        "comprimir imagem 100kb",
        "reduzir foto para 200kb",
        "tamanho limite foto",
        "comprimir para tamanho exato"
      ]
    },
    {
      "id": "image-cropper",
      "key": "imageCropper",
      "name": "Cortar imagem",
      "url": "/pt/ferramentas/recortar-imagem/",
      "category": "Editar",
      "desc": "Enquadre e corte suas imagens com facilidade na área interativa. Bloqueie proporções como quadrado 1:1, 4:3 ou panorâmico 16:9, ou defina livremente a área de recorte para destacar o essencial.",
      "keywords": [
        "cortar imagem",
        "recortar foto online",
        "crop imagem gratis",
        "corte quadrado 1:1",
        "cortar imagem 16:9"
      ]
    },
    {
      "id": "image-rotate-flip",
      "key": "imageRotateFlip",
      "name": "Girar e inverter imagem",
      "url": "/pt/ferramentas/girar-inverter-imagem/",
      "category": "Editar",
      "desc": "Corrija fotos que ficaram deitadas ao fotografar com o smartphone ou aplique efeitos de espelho. Gire 90° para a direita, 90° para a esquerda ou inverta a orientação horizontal e verticalmente.",
      "keywords": [
        "girar imagem",
        "inverter foto online",
        "espelhar imagem",
        "girar foto 90 graus",
        "corrigir orientacao foto"
      ]
    },
    {
      "id": "jpg-to-png",
      "key": "jpgToPng",
      "name": "JPG para PNG",
      "url": "/pt/ferramentas/jpg-para-png/",
      "category": "Converter",
      "desc": "Transforme fotos JPG em arquivos PNG de alta qualidade com compressão sem perdas. Perfeito para capturas de tela, logotipos e gráficos com contornos nítidos.",
      "keywords": [
        "jpg para png",
        "converter jpg em png",
        "transformar jpeg para png",
        "conversor png gratis",
        "mudar formato jpg para png"
      ]
    },
    {
      "id": "png-to-jpg",
      "key": "pngToGithubJpg",
      "name": "PNG para JPG",
      "url": "/pt/ferramentas/png-para-jpg/",
      "category": "Converter",
      "desc": "Transforme imagens PNG pesadas em arquivos JPG leves e universais. Substitua fundos transparentes por cores sólidas (como branco) e diminua o tempo de carregamento dos seus visuais.",
      "keywords": [
        "png para jpg",
        "converter png em jpg gratis",
        "tirar transparencia png para jpg",
        "reduzir peso png",
        "mudar formato png para jpg"
      ]
    },
    {
      "id": "webp-converter",
      "key": "webpConverter",
      "name": "Conversor WebP",
      "url": "/pt/ferramentas/conversor-webp/",
      "category": "Converter",
      "desc": "Transforme fotos JPG e PNG no formato WebP de última geração, ou converta arquivos WebP de volta para JPG e PNG. Acelere o carregamento das suas páginas e melhore suas métricas no Google PageSpeed.",
      "keywords": [
        "conversor webp",
        "converter para webp",
        "jpg para webp",
        "png para webp",
        "webp para jpg online",
        "formato webp"
      ]
    },
    {
      "id": "image-format-converter",
      "key": "imageFormatConverter",
      "name": "Conversor de formato de imagem",
      "url": "/pt/ferramentas/conversor-formato-imagem/",
      "category": "Converter",
      "desc": "Alterne entre os formatos JPG, PNG e WebP com facilidade, individualmente ou em lote. Controle a qualidade final, configure transparências e baixe suas imagens convertidas sem esperar upload em servidores.",
      "keywords": [
        "conversor formato imagem",
        "converter imagens em lote",
        "mudar formato foto online",
        "converter jpg png webp",
        "conversor multiplo de imagens"
      ]
    },
    {
      "id": "grayscale-image",
      "key": "grayscaleImage",
      "name": "Imagem em tons de cinza",
      "url": "/pt/ferramentas/imagem-tons-cinza/",
      "category": "Editar",
      "desc": "Transforme fotografias coloridas em elegantes imagens monocromáticas em preto e branco. Utiliza a fórmula padrão de luminância fotométrica para graduações de cinza naturais.",
      "keywords": [
        "foto preto e branco",
        "converter tons de cinza online",
        "filtro preto e branco",
        "desaturar imagem",
        "foto monocromatica"
      ]
    },
    {
      "id": "brightness-contrast",
      "key": "brightnessContrast",
      "name": "Brilho e contraste",
      "url": "/pt/ferramentas/brilho-contraste/",
      "category": "Editar",
      "desc": "Clareie fotos escuras, equilibre sombras e deixe as cores mais vivas com controles de alta precisão. Visualize tudo em tempo real e baixe imagens perfeitas sem complicação.",
      "keywords": [
        "brilho contraste online",
        "clarear foto escura",
        "aumentar contraste imagem",
        "ajustar exposicao foto",
        "saturacao de cores foto"
      ]
    },
    {
      "id": "blur-sharpen-image",
      "key": "blurSharpenImage",
      "name": "Desfocar e aumentar nitidez",
      "url": "/pt/ferramentas/desfocar-nitidez-imagem/",
      "category": "Editar",
      "desc": "Aplique um desfoque suave para ocultar detalhes do fundo ou aumente a nitidez dos contornos com matriz de convolução. Ajuste em tempo real com processamento 100% no seu dispositivo.",
      "keywords": [
        "desfocar imagem online",
        "aumentar nitidez foto",
        "desfoque gaussiano foto",
        "tornar foto nitida online",
        "realcar detalhes foto"
      ]
    },
    {
      "id": "image-color-picker",
      "key": "imageColorPicker",
      "name": "Conta-gotas de imagem",
      "url": "/pt/ferramentas/seletor-cor-imagem/",
      "category": "Cores",
      "desc": "Descubra os códigos de cor exatos em qualquer fotografia com nossa lupa de precisão de 8x. Analise pixels individuais, visualize códigos em HEX, RGB e HSL e copie-os para o seu projeto com um clique.",
      "keywords": [
        "conta gotas imagem online",
        "descobrir cor da foto",
        "pegar codigo hex imagem",
        "seletor de cores foto",
        "extrair rgb imagem"
      ]
    },
    {
      "id": "color-palette-generator",
      "key": "colorPaletteGenerator",
      "name": "Gerador de paleta de cores",
      "url": "/pt/ferramentas/gerador-paleta-cores/",
      "category": "Cores",
      "desc": "Extraia paletas de cores elegantes e equilibradas a partir de qualquer imagem ou foto de inspiração. Descubra os tons predominantes, veja os códigos HEX e baixe um cartão de amostras para suas apresentações.",
      "keywords": [
        "gerador paleta de cores",
        "extrair paleta de foto",
        "paleta de cores de imagem",
        "cores predominantes foto",
        "criar cartao de cores"
      ]
    },
    {
      "id": "favicon-generator",
      "key": "faviconGenerator",
      "name": "Gerador de favicon",
      "url": "/pt/ferramentas/gerador-favicon/",
      "category": "Criar",
      "desc": "Transforme o logotipo da sua marca em um pacote completo de favicons para o seu site. Gere ícones nos formatos 16x16, 32x32, 48x48 e Apple Touch de 180x180 com código HTML pronto para inserção no cabeçalho.",
      "keywords": [
        "gerador de favicon",
        "criar favicon online",
        "apple touch icon gerador",
        "icone para site",
        "codigo html favicon"
      ]
    },
    {
      "id": "image-to-base64",
      "key": "imageToBase64",
      "name": "Imagem para Base64",
      "url": "/pt/ferramentas/imagem-para-base64/",
      "category": "Desenvolvedor",
      "desc": "Transforme arquivos de imagem em strings Base64 e Data URLs. Incorpore imagens diretamente em tags HTML <img>, folhas de estilo CSS ou cargas úteis JSON sem precisar hospedar arquivos separadamente.",
      "keywords": [
        "imagem para base64",
        "converter foto em base64",
        "gerador data uri imagem",
        "incorporar imagem html css",
        "string base64 imagem"
      ]
    },
    {
      "id": "base64-to-image",
      "key": "base64ToImage",
      "name": "Base64 para imagem",
      "url": "/pt/ferramentas/base64-para-imagem/",
      "category": "Desenvolvedor",
      "desc": "Decodifique strings Base64 e Data URLs de volta para arquivos de imagem PNG, JPG ou WebP prontos para download. Valide a sintaxe do código e visualize suas fotos em segundos.",
      "keywords": [
        "base64 para imagem",
        "decodificar base64 em foto",
        "converter data uri para png",
        "string base64 em imagem online",
        "base64 para jpg"
      ]
    },
    {
      "id": "social-media-image-resizer",
      "key": "socialMediaImageResizer",
      "name": "Redimensionador para redes sociais",
      "url": "/pt/ferramentas/redimensionador-redes-sociais/",
      "category": "Redimensionar",
      "desc": "Enquadre suas fotos nas especificações exatas do Instagram, Facebook, YouTube, LinkedIn, TikTok e X. Elimine cortes indesejados e garanta posts com visual profissional.",
      "keywords": [
        "tamanho imagem instagram",
        "dimensoes miniatura youtube",
        "tamanho capa facebook",
        "banner linkedin medidas",
        "stories instagram tamanho"
      ]
    },
    {
      "id": "passport-photo-resizer",
      "key": "passportPhotoResizer",
      "name": "Redimensionador foto de passaporte",
      "url": "/pt/ferramentas/redimensionador-foto-passaporte/",
      "category": "Redimensionar",
      "desc": "Recorte e formate fotos para passaporte brasileiro, RG, CNH e vistos internacionais. Inclui guia biométrico para padrões 3x4 cm, europeu (35x45 mm) e visto americano (2x2 polegadas).",
      "keywords": [
        "foto 3x4 online",
        "recortar foto passaporte",
        "foto visto americano 2x2",
        "tamanho foto 35x45",
        "imprimir foto 3x4"
      ]
    },
    {
      "id": "meme-generator",
      "key": "memeGenerator",
      "name": "Gerador de memes",
      "url": "/pt/ferramentas/gerador-memes/",
      "category": "Criar",
      "desc": "Crie memes divertidos em segundos com o formato clássico de texto superior e inferior. Ajuste o tamanho da fonte, contornos e baixe suas piadas prontas para compartilhar sem nenhuma marca d'água.",
      "keywords": [
        "gerador de memes",
        "criar meme online gratis",
        "colocar texto em foto",
        "fazer meme na internet",
        "fonte impact meme"
      ]
    }
  ],
  "it": [
    {
      "id": "image-compressor",
      "key": "imageCompressor",
      "name": "Comprimi immagini",
      "url": "/it/strumenti/comprimi-immagine/",
      "category": "Compressione",
      "desc": "Riduci il peso dei tuoi file JPG, PNG e WebP in modo veloce, sicuro e senza perdita di qualità. Regola la qualità con il cursore in tempo reale, confronta il risultato prima e dopo e scarica l'immagine ottimizzata senza caricare file su server remoti.",
      "keywords": [
        "comprimi immagini",
        "riduci peso foto",
        "comprimere jpg",
        "comprimere png",
        "ridurre kb immagine",
        "ottimizzare foto online"
      ]
    },
    {
      "id": "image-resizer",
      "key": "imageResizer",
      "name": "Ridimensiona immagini",
      "url": "/it/strumenti/ridimensiona-immagine/",
      "category": "Ridimensiona",
      "desc": "Modifica la risoluzione delle tue foto impostando larghezza e altezza in pixel, percentuali o formati standard. Blocca le proporzioni per evitare deformazioni e scarica subito l'immagine con elaborazione locale.",
      "keywords": [
        "ridimensiona immagini",
        "cambia dimensioni foto",
        "modifica pixel immagine",
        "scalare foto online",
        "proporzioni immagine"
      ]
    },
    {
      "id": "image-to-target-size",
      "key": "imageToTargetSize",
      "name": "Comprimi a dimensione target",
      "url": "/it/strumenti/immagine-dimensione-target/",
      "category": "Compressione",
      "desc": "Devi caricare una foto con limite massimo di 50KB, 100KB o 200KB su un portale della pubblica amministrazione o per una candidatura? Imposta il peso target esatto e il nostro algoritmo calcolerà la qualità ottimale.",
      "keywords": [
        "comprimi a 50kb",
        "comprimi immagine 100kb",
        "riduci foto a 200kb",
        "dimensione target immagine",
        "peso limite foto"
      ]
    },
    {
      "id": "image-cropper",
      "key": "imageCropper",
      "name": "Ritaglia immagini",
      "url": "/it/strumenti/ritaglia-immagine/",
      "category": "Modifica",
      "desc": "Inquadra e ritaglia le tue foto con precisione grazie all'area di selezione interattiva. Blocca proporzioni standard come quadrato 1:1, 4:3, 16:9 panoramico o ritaglia a mano libera per evidenziare il soggetto principale.",
      "keywords": [
        "ritaglia immagini",
        "crop foto online",
        "ritagliare foto quadrato 1:1",
        "ritaglio 16:9",
        "ritaglia foto gratis"
      ]
    },
    {
      "id": "image-rotate-flip",
      "key": "imageRotateFlip",
      "name": "Ruota e capovolgi immagine",
      "url": "/it/strumenti/ruota-capovolgi-immagine/",
      "category": "Modifica",
      "desc": "Raddrizza foto scattate di traverso o capovolte dal tuo smartphone oppure crea effetti di riflesso speculare. Ruota di 90° in senso orario, antiorario o capovolgi in orizzontale e verticale.",
      "keywords": [
        "ruota immagine",
        "capovolgi foto online",
        "specchia immagine",
        "ruotare foto 90 gradi",
        "orientamento immagine smartphone"
      ]
    },
    {
      "id": "jpg-to-png",
      "key": "jpgToPng",
      "name": "JPG in PNG",
      "url": "/it/strumenti/jpg-in-png/",
      "category": "Converti",
      "desc": "Converti le tue foto JPG nel formato PNG senza perdita di qualità. Ottimale per screenshot, schemi e immagini con testi dove è richiesta la massima definizione dei bordi.",
      "keywords": [
        "jpg in png",
        "convertire jpg in png",
        "trasformare jpeg in png online",
        "convertitore png gratis",
        "formato png alta qualita"
      ]
    },
    {
      "id": "png-to-jpg",
      "key": "pngToGithubJpg",
      "name": "PNG in JPG",
      "url": "/it/strumenti/png-in-jpg/",
      "category": "Converti",
      "desc": "Converti file PNG pesanti in immagini JPG compatte e universali. Sostituisci la trasparenza con uno sfondo bianco o colorato e ottimizza i tuoi contenuti visivi per il web e la stampa.",
      "keywords": [
        "png in jpg",
        "convertire png in jpg",
        "trasformare png in jpeg gratis",
        "sostituire trasparenza png jpg",
        "alleggerire immagini png"
      ]
    },
    {
      "id": "webp-converter",
      "key": "webpConverter",
      "name": "Convertitore WebP",
      "url": "/it/strumenti/convertitore-webp/",
      "category": "Converti",
      "desc": "Converti le tue foto JPG e PNG nel moderno formato WebP a elevata efficienza, oppure converti file WebP in normali JPG e PNG. Velocizza il caricamento delle tue pagine web e migliora i punteggi Core Web Vitals.",
      "keywords": [
        "convertitore webp",
        "convertire in webp",
        "da jpg a webp",
        "da png a webp",
        "webp in jpg online",
        "formato immagini webp"
      ]
    },
    {
      "id": "image-format-converter",
      "key": "imageFormatConverter",
      "name": "Convertitore formato immagini",
      "url": "/it/strumenti/convertitore-formato-immagine/",
      "category": "Converti",
      "desc": "Converti immagini singole o serie di foto tra i formati JPG, PNG e WebP. Regola la qualità di output, gestisci la trasparenza e scarica i file convertiti all'istante senza passare da server esterni.",
      "keywords": [
        "convertitore formato immagini",
        "convertire immagini in batch",
        "cambiare formato foto online",
        "convertire jpg png webp",
        "convertitore universale foto"
      ]
    },
    {
      "id": "grayscale-image",
      "key": "grayscaleImage",
      "name": "Immagine in scala di grigi",
      "url": "/it/strumenti/immagine-scala-grigi/",
      "category": "Modifica",
      "desc": "Trasforma foto a colori in eleganti scatti monocromatici in bianco e nero. Applica la formula fotometrica standard ITU-R BT.709 per un contrasto armonico e sfumature di grigio naturali.",
      "keywords": [
        "foto bianco e nero online",
        "scala di grigi immagine",
        "convertire foto bianco e nero",
        "filtro monocromatico",
        "desatura colori foto"
      ]
    },
    {
      "id": "brightness-contrast",
      "key": "brightnessContrast",
      "name": "Luminosità e contrasto",
      "url": "/it/strumenti/luminosita-contrasto/",
      "category": "Modifica",
      "desc": "Schiarisci foto troppo scure, recupera le ombre e ravviva la saturazione dei colori con cursori precisi. Guarda le modifiche in tempo reale e scarica foto bilanciate senza software pesanti.",
      "keywords": [
        "luminosita contrasto online",
        "schiarire foto scura",
        "aumentare contrasto immagine",
        "regolare esposizione foto",
        "saturazione colori online"
      ]
    },
    {
      "id": "blur-sharpen-image",
      "key": "blurSharpenImage",
      "name": "Sfoca e aumenta nitidezza",
      "url": "/it/strumenti/sfoca-nitidezza-immagine/",
      "category": "Modifica",
      "desc": "Applica una sfocatura morbida per attenuare elementi di disturbo sullo sfondo oppure aumenta la nitidezza dei contorni con una matrice di convoluzione. Preciso, rapido e privato.",
      "keywords": [
        "sfoca immagine online",
        "aumentare nitidezza foto",
        "sfocatura gaussiana online",
        "foto nitida online",
        "filtro nitidezza immagine"
      ]
    },
    {
      "id": "image-color-picker",
      "key": "imageColorPicker",
      "name": "Contagocce immagini",
      "url": "/it/strumenti/selettore-colore-immagine/",
      "category": "Colore",
      "desc": "Estrai i codici colore esatti da qualsiasi fotografia grazie alla lente d'ingrandimento a 8 ingrandimenti. Ispeziona singoli pixel, scopri valori HEX, RGB e HSL e copiali con un clic per i tuoi progetti grafici e web.",
      "keywords": [
        "contagocce immagini online",
        "trovare codice hex da foto",
        "campionare colori immagine",
        "selettore colori online",
        "estrarre rgb foto"
      ]
    },
    {
      "id": "color-palette-generator",
      "key": "colorPaletteGenerator",
      "name": "Generatore tavolozza colori",
      "url": "/it/strumenti/generatore-tavolozza-colori/",
      "category": "Colore",
      "desc": "Estrai armoniose palette cromatiche dalle tue fotografie e opere grafiche preferite. Scopri le tinte dominanti, consulta i codici HEX e scarica una scheda campione elegante da utilizzare nei tuoi progetti di design.",
      "keywords": [
        "generatore palette colori",
        "estrarre colori da foto",
        "palette da immagine online",
        "colori dominanti foto",
        "creare campionario colori"
      ]
    },
    {
      "id": "favicon-generator",
      "key": "faviconGenerator",
      "name": "Generatore favicon",
      "url": "/it/strumenti/generatore-favicon/",
      "category": "Crea",
      "desc": "Trasforma il tuo logo in un set completo di favicon per qualsiasi sito internet. Genera le misure standard 16x16, 32x32, 48x48 e 180x180 per Apple Touch Icon con codice HTML pronto da copiare nel tuo header.",
      "keywords": [
        "generatore favicon",
        "creare favicon online",
        "apple touch icon generatore",
        "icona scheda sito web",
        "codice html favicon"
      ]
    },
    {
      "id": "image-to-base64",
      "key": "imageToBase64",
      "name": "Immagine in Base64",
      "url": "/it/strumenti/immagine-in-base64/",
      "category": "Sviluppatore",
      "desc": "Converti file di immagine in stringhe codificate Base64 e Data URL. Incorpora immagini direttamente nei tag HTML <img>, proprietà CSS background-image o payload JSON senza generare richieste HTTP esterne.",
      "keywords": [
        "immagine in base64",
        "convertire foto in base64",
        "generatore data uri",
        "incorporare immagine html css",
        "stringa base64 immagine"
      ]
    },
    {
      "id": "base64-to-image",
      "key": "base64ToImage",
      "name": "Base64 in immagine",
      "url": "/it/strumenti/base64-in-immagine/",
      "category": "Sviluppatore",
      "desc": "Decodifica stringhe Base64 e Data URL per ottenere file di immagine PNG, JPG o WebP scaricabili e pronti all'uso. Valida la correttezza del codice e visualizza le anteprime in un istante.",
      "keywords": [
        "base64 in immagine",
        "decodificare base64 in foto",
        "convertire data uri in png",
        "trasformare stringa base64 in jpg",
        "base64 to image online"
      ]
    },
    {
      "id": "social-media-image-resizer",
      "key": "socialMediaImageResizer",
      "name": "Ridimensiona per social media",
      "url": "/it/strumenti/ridimensiona-social-media/",
      "category": "Ridimensiona",
      "desc": "Adatta le tue immagini ai formati ufficiali di Instagram, Facebook, YouTube, LinkedIn, TikTok e X. Elimina i ritagli automatici sgraditi e presenta post graficamente impeccabili su ogni dispositivo.",
      "keywords": [
        "dimensioni immagini instagram",
        "miniatura youtube formato",
        "copertina facebook misure",
        "storia instagram dimensioni",
        "banner linkedin formato"
      ]
    },
    {
      "id": "passport-photo-resizer",
      "key": "passportPhotoResizer",
      "name": "Ridimensiona foto passaporto",
      "url": "/it/strumenti/ridimensiona-foto-passaporto/",
      "category": "Ridimensiona",
      "desc": "Ritaglia e adatta fototessere per passaporto italiano, carta d'identità elettronica (CIE) e visti internazionali. Guida biometrica conforme agli standard ICAO (35x45 mm) e visto USA (2x2 pollici).",
      "keywords": [
        "fototessera 35x45 online",
        "foto passaporto formato",
        "foto carta identita elettronica",
        "foto visto usa 2x2",
        "stampare fototessere"
      ]
    },
    {
      "id": "meme-generator",
      "key": "memeGenerator",
      "name": "Generatore di meme",
      "url": "/it/strumenti/generatore-meme/",
      "category": "Crea",
      "desc": "Crea meme virali in pochi istanti con la classica scritta sopra e sotto. Personalizza dimensioni del testo, contorno nero e scarica i tuoi meme pronti da condividere sui social senza alcuna filigrana pubblicitaria.",
      "keywords": [
        "generatore di meme",
        "creare meme online gratis",
        "scrivere testo su foto",
        "fare meme gratis",
        "font impact meme"
      ]
    }
  ]
};
